builds: 
  - binary: syro-cli-alpha
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: syro-cli-alpha
    homepage: https://github.com/danlemuelsalado/syro-cli-alpha
    tap:
      owner: danlemuelsalado
      name: syro-cli-alpha
    commit_author:
      name: danlemuelsalado
      email: danlemuelsalado@gmail.com

checksum: 
  name_template: 'checksums.txt'