# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SyroCliAlpha < Formula
  desc ""
  homepage "https://github.com/danlemuelsalado/syro-cli-alpha"
  version "0.0.1"

  on_macos do
    url "https://github.com/danlemuelsalado/syro-cli-alpha/releases/download/v0.0.1/syro-cli-alpha_0.0.1_darwin_all.tar.gz"
    sha256 "15b77256122dc6d33e570e6c086ae334968c577ed40f16da81628b809f98ad36"

    def install
      bin.install "syro-cli-alpha"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danlemuelsalado/syro-cli-alpha/releases/download/v0.0.1/syro-cli-alpha_0.0.1_linux_arm64.tar.gz"
      sha256 "95753c3895953ce203de98668e180ab432ea054e53014f7832ce71e51962640f"

      def install
        bin.install "syro-cli-alpha"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/danlemuelsalado/syro-cli-alpha/releases/download/v0.0.1/syro-cli-alpha_0.0.1_linux_amd64.tar.gz"
      sha256 "2de942c7b08c503cf4ed1901b488ed2519e72a9cc9d951a1596d66c22e6f327a"

      def install
        bin.install "syro-cli-alpha"
      end
    end
  end
end
